baseurl = "/"
title = "Blog | 酷儿论坛"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"

metaDataFormat = "yaml"
hasCJKLanguage = true

theme = "mainroad"
paginate = 10
paginatePath = "page"

#disqusShortname = ""
#googleAnalytics = ""

# [menu]
#   [[menu.main]]
#     identifier = "bbs"
#     name = "进入论坛"
#     url = "https://bbs.motss.info"
#     weight = -110

[Author]
    name = "Blog | MOTSS Forum"

[Params]
  subtitle = "论坛上的存货"
  description = "" 
  opengraph = true
  twitter_cards = true 
  readmore = false 
  authorbox = false 
  toc = false 
  post_navigation = true 
  postSections = ["post"] 
  highlightColor = "#3da742" # Override highlight color
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.sidebar]
  home = "right" 
  list = "left"  
  single = false 
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 
  tags_counter = false 

[Params.widgets.social]
#   facebook = "username"
#   twitter = "username"
#   linkedin = "username"
#   telegram = "username"
  github = "MOTSS-forum"
  email = "motss@motss.info"
#   google_plus = "profileid"
